###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:11-alpine'
        working_dir: /app
        volumes:
            - './app:/app'
        environment:
            - POSTGRES_USER=redoc_azk
            - POSTGRES_PASSWORD=Aziz007td
            - POSTGRES_DB=dofi
        ports:
            - '40004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '40000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - './app:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
